plugins {
    id 'com.android.application'
}

android {
    namespace 'it.dossiersanitario.checkpointsmoke'
    compileSdk 35

    defaultConfig {
        applicationId 'it.dossiersanitario.checkpointsmoke'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
}

dependencies {
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
